unit TestKnuthMorrisPratt;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, System.Variants, knuthMorrisPratt, dynamicArray,
  System.Classes;

type
  // Test methods for class TKnuthMorrisPratt

  TestTKnuthMorrisPratt = class(TTestCase)
  strict private
    FKnuthMorrisPratt: TKnuthMorrisPratt;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestknuthMorrisPratt;
  end;

implementation

procedure TestTKnuthMorrisPratt.SetUp;
begin
  FKnuthMorrisPratt := TKnuthMorrisPratt.Create;
end;

procedure TestTKnuthMorrisPratt.TearDown;
begin
  FKnuthMorrisPratt.Free;
  FKnuthMorrisPratt := nil;
end;

procedure TestTKnuthMorrisPratt.TestknuthMorrisPratt;
var
  ReturnValue: Integer;
  word: string;
  text: string;
begin

  Assert(FKnuthMorrisPratt.knuthMorrisPratt('', '') = 0);
  Assert(FKnuthMorrisPratt.knuthMorrisPratt('a', '') = 0);
  Assert(FKnuthMorrisPratt.knuthMorrisPratt('a', 'a') = 0);
  Assert(FKnuthMorrisPratt.knuthMorrisPratt('abcbcglx', 'abca') = -1);
  Assert(FKnuthMorrisPratt.knuthMorrisPratt('abcbcglx', 'bcgl') = 3);
  Assert(FKnuthMorrisPratt.knuthMorrisPratt('abcxabcdabxabcdabcdabcy', 'abcdabcy') = 15);
  Assert(FKnuthMorrisPratt.knuthMorrisPratt('abcxabcdabxabcdabcdabcy', 'abcdabca') = -1);
  Assert(FKnuthMorrisPratt.knuthMorrisPratt('abcxabcdabxaabcdabcabcdabcdabcy', 'abcdabca') = 12);
  Assert(FKnuthMorrisPratt.knuthMorrisPratt('abcxabcdabxaabaabaaaabcdabcdabcy', 'aabaabaaa') = 11);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTKnuthMorrisPratt.Suite);
end.

